### ISSUE TITLE
请问能否先把文件内容输出到ws，然后再动态一行一行输出呢

### ISSUE THREAD

**Issue by lifa1225** [xmge/seelog#15]

**Comment by xmge** [comment]
本版本没有直接向浏览器上输出，可自行更改相关代码来实现一下。

**Comment by xmge** [comment]
监听的是文件

**Comment by lifa1225** [comment]
感谢回复，也不是输出到浏览器，我看你的代码实现是输出到websocket，其实就是先把文件的内容全部输出到websocket，然后再监听

**Comment by xmge** [comment]
我可能没有听明白。

这个项目的目的是 把日志文件输出到浏览器上，可以通过浏览器来查看日志，不用登录服务器了。

所以核心代码主要是：
1、监控日志文件是否有数据输入，如果有输入则放入待发送的channel里
2、创建websocket服务端，然后浏览器访问时，则与它建立链接websocket链接。
3、for遍历channel，如果channel中有数据，则向所有websocket客户度发送信息

**Comment by lifa1225** [comment]
![image](https://user-images.githubusercontent.com/59470742/77042935-7fc9ed80-69f7-11ea-94e5-1a4a7210bf58.png)
比如说我第一次打开这个监控，里面是什么内容的没有的，但是我的文件err.log是已经有内容了，我想把原有的内容也同时输出来。
![image](https://user-images.githubusercontent.com/59470742/77043103-c7e91000-69f7-11ea-9d90-df67b6063735.png)

**Comment by xmge** [comment]
这个需求就不是这个项目的目的了。

可以直接搭载个nginx，用浏览器就可以直接看日志了。
