### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by IamQiuTian** [xmge/seelog#6]
希望可以在有多种日志的情况下， 进行选择。

**Comment by xmge** [comment]
也就是说可以在浏览器上可以监控多个文件吗？

**Comment by IamQiuTian** [comment]
可以在后端 配置需要监控的多个文件 在前端可以用列表选择  看哪个日志文件的实时内容。

**Comment by zbaolong** [comment]
大神，QQ联系方式。帮忙指导一下。1254225146。

**Comment by xmge** [comment]
这个功能正在开发中

**Comment by xmge** [comment]
@IamQiuTian 多文件监控，已经完成，使用有什么疑问可以咨询。
